name: t2sz
base: core20
version: '1.1.1'
summary: It compress any file into a seekable .zstd file
description: |
  It compress a file into a seekable zstd splitting the file into multiple frames.
  If the file is a tar archive it compress each file in the archive into an independent frame, hence the name: tar 2 seekable zstd.
  This allows fast seeking and extraction of a single file without decompressing the whole archive.
  The compressed archive can be uncompressed with any Zstandard tool, including zstd, and it can also be mounted with ratarmount.
  

grade: stable
confinement: strict

parts:
  t2sz:
    plugin: cmake
    source: .
    build-packages:
      - libzstd-dev

apps:
  t2sz:
    command: usr/local/bin/t2sz
    plugs:
      - home
      - removable-media
